pg 16 support
pgpartman/pg_partman pull request #508
Opened 2023-02-15 04:46 UTC by RekGRpth

2023-03-22 19:40 UTC, keithf4 requested changes

2023-03-23 03:52 UTC, RekGRpth commented on src/pg_partman_bgw.c
> +PGDLLEXPORT void pg_partman_bgw_main(Datum);
> Also can you point to the commit/email thread that talks about what this change is? Just curious.

https://github.com/postgres/postgres/commit/089480c077056fc20fa8d8f5a3032a9dcf5ed812

2023-03-23 03:55 UTC, RekGRpth commented on src/pg_partman_bgw.c
> +PGDLLEXPORT void pg_partman_bgw_main(Datum);
> Is this something specific to PG16 or will this be backward compatible to PG14 and 15?

I successfully compile pg_partman with this patch on versions 9.4, 9.5, 9.6, 10, 11, 12, 13, 14, 15 and 16 in my repo https://github.com/RekGRpth/postgres.docker

2023-04-28 13:29 UTC, merged

2023-04-28 13:29 UTC, keithf4 commented
Thank you!